{% set version = "3.4.2" %}

package:
  name: networkx
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/networkx/networkx-{{ version }}.tar.gz
  sha256: 307c3669428c5362aab27c8a1260aa8f47c4e91d3891f48be0141738d8d053e1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - setuptools >=61.2
    - pip
  run:
    - python >=3.10
  run_constrained:
    - numpy >=1.24
    - scipy >=1.10,!=1.11.0,!=1.11.1
    - matplotlib >=3.7
    - pandas >=2.0

test:
  imports:
    - networkx
    - networkx.algorithms
    - networkx.algorithms.assortativity
    - networkx.algorithms.bipartite
    - networkx.algorithms.centrality
    - networkx.algorithms.community
    - networkx.algorithms.components
    - networkx.algorithms.connectivity
    - networkx.algorithms.coloring
    - networkx.algorithms.flow
    - networkx.algorithms.minors
    - networkx.algorithms.traversal
    - networkx.algorithms.isomorphism
    - networkx.algorithms.shortest_paths
    - networkx.algorithms.link_analysis
    - networkx.algorithms.operators
    - networkx.algorithms.approximation
    - networkx.algorithms.tree
    - networkx.classes
    - networkx.generators
    - networkx.drawing
    - networkx.linalg
    - networkx.readwrite
    - networkx.readwrite.json_graph
    - networkx.tests
    - networkx.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://networkx.github.io/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Python package for creating and manipulating complex networks
  description: |
    NetworkX is a Python language software package for the creation,
    manipulation, and study of the structure, dynamics, and functions of complex
    networks.
  doc_url: https://networkx.org/documentation/stable/
  dev_url: https://github.com/networkx/networkx

extra:
  recipe-maintainers:
    - Schefflera-Arboricola
    - stefanv
    - synapticarbors
    - ocefpaf
    - SylvainCorlay
    - FelixMoelder
    - MridulS
